### ISSUE TITLE
Refresh blaze template

### ISSUE THREAD

**Issue by joaopiopedreira** [gadicc/meteor-blaze-react-component#13]
Hi, @gadicc , I have a react modal rendering a blaze template inside it. I note, however, as long as the react parent context is the same, the template remains unchanged (doesn't refresh on modal opening). I have a form in the template with some fields. When the user opens the modal, he sees the template state as it left it the last time the modal was opened. 

Is there a way to refresh the template when it's opened? Thanks.

**Comment by gadicc** [comment]
Hi @joaopiopedreira, sorry, I realize this issue is from over a year ago.  I'm closing as I assume it's no longer relevant.  On the off chance that it is, please let me know and I'll give it my full attention.

In general these kind of issues involve the intricacies of blaze/react indivdiually and don't relate specifically to this package, nevertheless, it's useful to collect these kind of issues here for the benefit of others.  If still relevant, please give some sample code of how everything is declared and I can suggest some strategies.
