### ISSUE TITLE
span tag in the templates

### ISSUE THREAD

**Issue by hmontes** [gadicc/meteor-blaze-react-component#4]
Hi

Can i remove the "span" tag generated by this plugin? I want to put meteor useraccounts in a modal but the span disable all the css in that component.

Thanks

**Comment by gadicc** [comment]
Hey, unfortunately not.  Blaze components *have to* be rendered into an element.  You don't usually feel this because you can include Blaze components into other Blaze components without this restriction, but the ultimate root render has to be into an HTML element, and we use the SPAN for that.

Can you explain how this affects the CSS though?  My original use case for this package was accounts-ui and it works without a problem.  Hopefully this is something we can solve with just CSS rule tweaks.

**Comment by Captain-GaDo** [comment]
I try to put the login form in a modal.

```
<div className="ui modal">
        <i className="close icon"></i>
          <Blaze template="atForm" />
      </div>
```

I modified the accounts template. Something like.
```

<div class="at-form">
      {{#if showTitle}}
        <div class="header">
          {{> atTitle}}
        </div>
      {{/if}}
      <div class="content">
        {{#if showOauthServices}}
....

But i losted all the css customization because the span (and the class="at-form" but i can remove that). I can change your span tag for a div?

I'll try another css customization.

Thanks
```

**Comment by gadicc** [comment]
Sorry, this reply got lost amongst other issues :(  Did you figure it out?  I still believe this is a CSS issue.  Thanks also for your kind words.

**Comment by Praxie** [comment]
@hmontes @gadicc this may be a simple workaround
https://github.com/gadicc/meteor-blaze-react-component/pull/6

**Comment by gadicc** [comment]
Good point, this is the way to go.  Thanks for the PR.  In short (for others), you can now specify a `className` attribute for the `<span>` tag (with, for example, a class like `display: block` to make it behave like a `<div>`).  Considering this issue closed unless I hear otherwise.
